(library (algebra commutative)
         (export expression)
         (import (rnrs (6))
                 (format format)
                 (utility yasos)
                 (algebra rings)
                 (algebra internal commutative))

  (define (expression a)
    (object
      ((ring? self) #t)
      ((repr self) (format "{}" a))
      ((unbox self) a)
      ((like self n) (expression n))
      ((:one? self) (eq? a 1))
      ((:zero? self) (eq? a 0))
      ((:+: self other) (expression (expand (add a (unbox other)))))
      ((:*: self other) (expression (expand (mul a (unbox other)))))
      ((:-: self other) (expression (expand (add a (unbox (negate other))))))
      ((negate self)    (expression (expand (mul -1 a))))))
)
